# -*- coding: utf-8 -*-
"""WEEK-1 TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OM1G-ALocp_9WDPgDLRy_QV6ZfAnYMxI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"C:\Users\maria\Downloads\Logistics_Week1_GitHub_Ready\dataset\logistics_sample_data.csv"

import zipfile
import os

# The zip file is already uploaded in the workspace
zip_path = 'Logistics_Week1_GitHub_Ready.zip'

# Extract the zip file
if os.path.exists(zip_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall('extracted_data')
    print("Extraction complete!")

# Locate and load the CSV file
# Since it was zipped, we look inside the extracted folder
target_csv_suffix = 'logistics_sample_data.csv'
csv_path = None

for root, dirs, files in os.walk('extracted_data'):
    for file in files:
        if file.endswith(target_csv_suffix):
            csv_path = os.path.join(root, file)
            break

if csv_path:
    df = pd.read_csv(csv_path)
    print("Shape:", df.shape)
    display(df.head())
else:
    print("Could not find the logistics_sample_data.csv file in the extracted archive.")

print(df.info())
print(df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())

date_cols = ["order_date", "promised_date", "actual_delivery_date"]
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")
df = df.drop_duplicates()
df = df.dropna(subset=date_cols + ["delivery_cost", "quantity", "distance_km"])
df = df[(df["quantity"] >= 0) & (df["delivery_cost"] >= 0) & (df["distance_km"] >= 0)]
print("Cleaned shape:", df.shape)

df["delivery_days"] = (df["actual_delivery_date"] - df["order_date"]).dt.days
df["on_time"] = df["actual_delivery_date"] <= df["promised_date"]
df["order_month"] = df["order_date"].dt.to_period("M").astype(str)
on_time_rate = df["on_time"].mean() * 100
avg_delivery_days = df["delivery_days"].mean()
cost_per_order = df["delivery_cost"].sum() / df["order_id"].nunique()
print(f"On-time delivery rate: {on_time_rate:.2f}%")
print(f"Average delivery time: {avg_delivery_days:.2f} days")
print(f"Transportation cost per order: {cost_per_order:.2f}")

df["delivery_days"].hist(bins=15, figsize=(8,4))
plt.title("Distribution of Delivery Time")
plt.xlabel("Delivery time (days)")
plt.ylabel("Number of orders")
plt.tight_layout()
plt.show()

df.groupby("location")["delivery_cost"].mean().plot(kind="bar",
figsize=(8,4), title="Average Delivery Cost by Location")
plt.ylabel("Average cost")
plt.tight_layout()
plt.show()

df.groupby("order_month")["order_id"].nunique().plot(kind="line",
marker="o", figsize=(10,4),
title="Monthly Order Count")
plt.xticks(rotation=45);
plt.tight_layout();
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

X = df[["distance_km", "quantity"]]
y = df["delivery_days"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

features = df[["distance_km", "quantity", "delivery_cost"]]
scaled = StandardScaler().fit_transform(features)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df["delivery_cluster"] = kmeans.fit_predict(scaled)
print(df.groupby("delivery_cluster")[["distance_km","quantity","delivery_cost"]].mean().round(2))
print("Silhouette score:", round(silhouette_score(scaled, df["delivery_cluster"]), 3))

print("WEEK-1 TASK IS COMPLETED")